spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${database-host}:3306/huruhuru?createDatabaseIfNotExist=true
      username: huruhuru
      password: ${database-password}
#    url: jdbc:h2:tcp://localhost/~/huruhuru
#    username: sa
#    password:

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

#  jpa:
#    open-in-view: true
#    hibernate:
#    properties:
#      hibernate:
#        hibernate.hbm2ddl.auto: update
#        format_sql: true
#    show_sql: true

jwt:
  secret: service-fit-secret-key

logging.level:
  org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: huruhuru
    region:
      static: ap-northeast-2
    stack:
      auto: false
#    credentials:
#      access-key:
#      secret-key:


#logging:
#  level:
#    org:
#      springframework: debug